apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
  labels:
    app: nextjs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: nextjs
          image: ghcr.io/satishganiyada/nextjs-application:v28
          imagePullPolicy: Always
          ports:
            - containerPort: 3000