name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag satish2323/nextjs-app:v${{ github.run_number }}
    - name: check images
      run: docker images
    - name: docker login
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD_TOKEN }}
    - name: pushing image
      run: docker push satish2323/nextjs-app:v${{ github.run_number }}
      